name: metadrive_ma_blocks_selected_9env
sampling: uniform
tasks:
  - id: straight
    env_config: metadrive_ma_block_straight
  - id: curve
    env_config: metadrive_ma_block_curve
  - id: roundabout
    env_config: metadrive_ma_roundabout
  - id: intersection
    env_config: metadrive_ma_intersection
  - id: in_ramp
    env_config: metadrive_ma_in_ramp
  - id: t_intersection
    env_config: metadrive_ma_t_intersection
  - id: bottleneck
    env_config: metadrive_ma_bottleneck
  - id: merge
    env_config: metadrive_ma_block_merge
  - id: split
    env_config: metadrive_ma_block_split
